service: product

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getProductsList:
    handler: build/functions/getProductsList.getProductsList
    events:
      - httpApi:
          path: '/product'
          method: 'GET'
          cors: true

  getProductsById:
    handler: build/functions/getProductsById.getProductsById
    events:
      - httpApi:
          path: '/product/{id}'
          method: 'GET'
          cors: true

  createProduct:
    handler: build/functions/createProduct.createProduct
    events:
      - httpApi:
          path: '/product'
          method: 'POST'
          cors: true
package:
  excludeDevDependencies: false
  exclude:
    - src/**
    - tsconfig.json
    - README.md
