service: product

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getProductsList:
    handler: src/functions/getProductsList.handler
    events:
      - httpApi:
          path: '/product'
          method: 'GET'
          cors: true

  getProductsById:
    handler: src/functions/getProductsById.handler
    events:
      - httpApi:
          path: '/product/{id}'
          method: 'GET'
          cors: true

  createProduct:
    handler: src/functions/createProduct.handler
    events:
      - httpApi:
          path: '/product'
          method: 'POST'
          cors: true
# package:
#   excludeDevDependencies: false
#   exclude:
#     - src/**
#     - tsconfig.json
#     - README.md
